services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: penyetan
      POSTGRES_USER: penyetan
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://penyetan:password@postgres:5432/penyetan

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`penyetan-api.bra-dev.com`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls=true'
      - 'traefik.http.routers.backend.tls.certresolver=mytlschallenge'
      - 'traefik.http.services.backend.loadbalancer.server.port=8000'

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: 'https://penyetan-api.bra-dev.com'

    restart: always

    ports:
      - '3000:3000'

    depends_on:
      - backend

    environment:
      NEXT_PUBLIC_API_URL: 'https://penyetan-api.bra-dev.com'

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`penyetan-do.bra-dev.com`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls=true'
      - 'traefik.http.routers.frontend.tls.certresolver=mytlschallenge'
      - 'traefik.http.services.frontend.loadbalancer.server.port=3000'

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: n8n_default
